nouns_singular = ["time", "year", "people", "way", "day", "man", "thing", "woman", "life",
    "world", "school", "state", "family", "student", "group", "country", "problem",  "child", 
    "hand", "part", "place", "case", "week", "company", "system", "program", "question", 
    "work", "government", "number", "night", "point", "home", "water", "room", "mother", 
    "area", "money", "story", "fact", "month", "lot", "right", "study", "book", "eye", 
    "job", "word", "business", "issue", "side", "kind", "head", "house", "service", 
    "friend", "father", "power", "hour", "game", "line", "end", "member", "law", "car", 
    "city", "community", "name", "president", "team", "minute", "idea", "kid", "body", 
    "information", "back", "parent", "face", "others", "level", "office", "door", 
    "health", "person", "art", "war", "history", "party", "result", "change", "morning", 
    "reason", "research", "girl", "guy", "moment", "air", "teacher", "force", "education", 
    "foot", "boy", "age", "policy", "process", "music", "market", "sense", "nation", 
    "plan", "college", "interest", "death", "experience", "effect", "use", "class", 
    "control", "care", "field", "development", "role", "effort", "rate", "heart", "drug", 
    "show", "leader", "light", "voice", "wife", "police", "mind", "price", "report", 
    "decision", "son", "view", "relationship", "town", "road", "army", "operation", 
    "run", "patient", "past", "defense", "stage", "writer", "concept", "challenge", 
    "friendship", "right", "growth", "trip", "evening", "argument", "lot", "ability", 
    "player", "video", "equipment", "picture", "agency", "thousand", "player", "unit", 
    "citizen", "round", "line", "issue", "security", "peace", "capital", "behavior", 
    "date", "impact", "airport", "branch", "emergency", "outside", "beautiful", "cabinet", 
    "childhood", "church", "clothes", "coffee", "construction", "cup", "employment", 
    "engine", "entry", "fail", "fight", "finger", "flower", "glass", "hospital", "loan", 
    "noise", "payment", "penalty", "pool", "poster", "pot", "salary", "shock", "sister", 
    "soup", "caption", "spirit", "struggle", "suit", "table", "throat", "tune", "vacation", 
    "village", "warning", "weekend", "writer", "yard", "anger", "battle", "beauty", "beginning", 
	"breath", "brother", "buddy", "camera", "camp", "candy", "cattle", "chance", "chapter", 
	"clock", "comfort", "committee", "conversation", "cookie", "courage", "dad", "darkness", 
	"desk", "dinner", "drawing", "ear", "ease", "entrance", "equipment", "error", "expense", 
	"face", "farm", "fat", "flight", "flower", "food", "freedom", "friendship", "funeral", 
	"gene", "gift", "girlfriend", "golf", "government", "grain", "grandmother", "guest", 
	"guidance", "guitar", "hair", "health", "heat", "height", "hell", "highlight", "home", 
	"homework", "honey", "horse", "host", "household", "hunger", "impression", "insurance", 
	"jacket", "jelly", "joy", "judgment", "jury", "justice", "keyboard", "king", "knife", 
	"knowledge", "lab", "land", "lawyer", "lecture", "legacy", "leisure", "lesson", "letter", 
	"library", "license", "life", "listener", "liver", "local", "location", "lunch", "mall", 
	"marriage", "meal", "meaning", "medicine", "memory", "method", "middle", "mind", "minority", 
	"mixture", "mom", "mood", "motor", "movie", "muscle", "nail", "neck", "nephew", "nerve", 
	"newspaper", "nightmare", "noise", "note", "novel", "nurse", "object", "occasion", 
	"offer", "oil", "operation", "opinion", "orange", "owner", "page", "painting", "palm", 
	"pension", "personality", "photography", "physics", "piano", "piece", "pillow", "place", 
	"planet", "plate", "pleasure", "poem", "poetry", "policeman", "pool", "pop", "portion", 
	"post", "potato", "powder", "prayer", "preference", "presence", "pressure", "pride", 
	"priest", "prize", "profession", "promise", "property", "protection", "punishment", 
	"purpose", "quantity", "queen", "reaction", "reflection", "refrigerator", "region", 
	"relationship", "religion", "reminder", "repair", "replacement", "representative", 
	"reservation", "resolution", "respect", "responsibility", "revenge", "reward", "rice", 
	"rifle", "ring", "roof", "roommate", "satisfaction", "sauce", "scene", "scent", "school", 
	"science", "scratch", "season", "security", "selection", "sensitivity", "sentence", 
	"sequence", "sergeant", "seriousness", "shadow", "shame", "shelf", "shirt", "shoe", 
	"shopping", "shower", "sibling", "signature", "singer", "sir", "sister", "skill",
	"snow", "soap", "soccer", "sock", "solution", "son", "song", "soup", "specialist", 
	"caption", "spending", "spirit", "spite", "spoon", "sport", "spot", "spread", "spring", 
	"squad", "stability", "stack", "staircase", "stand", "standard", "state", "statistics", 
	"status", "steam", "steak", "step", "stomach", "stone", "stop", "stranger", "strength", 
	"stroke", "structure", "substance", "success", "suggestion", "summer", "sun", "sunset", 
	"supermarket", "support", "surgery", "surprise", "sweater", "sweetheart", "swimming", 
	"table", "talent", "tea", "teacher", "teaching", "team", "television", "temperature", 
	"tenant", "tendency", "tennis", "test", "thanks", "theory", "therapy", "thirst", "throat", 
	"ticket", "tiger", "title", "tooth", "top", "tourist", "towel", "tower", "toy", "track", 
	"tradition", "traffic", "tragedy", "transaction", "transmission", "travel", "tree", 
	"trick", "trouble", "trust", "truth", "uncle", "understanding", "union", "university", 
	"update", "upper", "vacation", "valley", "value", "variety", "vegetable", "vehicle", 
	"village", "violence", "vision", "visit", "voice", "volunteer", "warning", "wash", 
	"watch", "water", "wealth", "weather", "weekend", "weight", "western", "wheel", 
	"wilderness", "wind", "window", "wine", "winner", "winter", "wish", "witness", "woman", 
	"wood", "word", "work", "world", "worry", "worth", "wound", "writer", "yard", "anger", 
	"battle", "beauty", "beginning", "belief", "bottle", "breath", "brother", "buddy", 
	"camera", "camp", "candy", "cattle", "chance", "chapter", "clock", "comfort", "committee", 
	"conversation", "cookie", "courage", "dad", "darkness", "desk", "dinner", "drawing", "ear", 
	"ease", "entrance", "equipment", "error", "expense", "face", "farm", "fat", "flight", 
	"flower", "food", "freedom", "friendship", "funeral", "gene", "gift", "girlfriend", 
	"golf", "government", "grain", "grandmother", "guest", "guidance", "guitar", "hair", 
	"health", "heat", "height", "hell", "highlight", "home", "homework", "honey", "horse", 
	"host", "household", "hunger", "impression", "insurance", "jacket", "jelly", "jewelry", 
	"laughter", "law", "leadership", "leather", "leisure", "lesson", "library", "lifestyle",
	"light", "limit", "lion", "lip", "liquid", "list", "liver", "load", "local", "logic",
	"luck", "lunch", "lung", "machine", "magazine", "mail", "main", "management", "marriage",
	"math", "meal", "meaning", "memory", "message", "metal", "method", "milk", "mixture",
	"mode", "moment", "morning", "mother", "motion", "mouth", "move", "music", "nation",
	"nature", "neighbor", "nephew", "nerve", "net", "news", "night", "nose", "notion",
	"novel", "number", "objective", "obligation", "occasion", "office", "oil", "opinion",
	"opportunity", "option", "order", "organ", "organization", "outcome", "output", "oven",
	"owner", "package", "pain", "painting", "pair", "parent", "park", "part", "partner",
	"passenger", "past", "patience", "pattern", "pause", "pay", "peace", "perception",
	"performance", "period", "permission", "personality", "pet", "phase", "philosophy",
	"phone", "photography", "physics", "piano", "picture", "piece", "pin", "pizza", "place",
	"plan", "plastic", "plate", "platform", "pleasure", "poem", "poetry", "point", "poker",
	"police", "pollution", "pop", "population", "portion", "position", "possibility",
	"post", "pot", "potato", "power", "preference", "preparation", "presence", "presentation",
	"president", "pressure", "price", "pride", "primary", "print", "priority", "problem",
	"process", "product", "profession", "profit", "program", "project", "promotion", "property",
	"protection", "psychology", "public", "publication", "punch", "quality", "quantity",
	"queen", "question", "quiet", "quit", "race", "radio", "rain", "range", "reaction",
	"reading", "reality", "reason", "reception", "recipe", "recognition", "recommendation",
	"record", "reflection", "refrigerator", "refuse", "region", "register", "relation",
	"relationship", "release", "relevance", "relief", "religion", "remains", "reminder",
	"remote", "rent", "repair", "replacement", "report", "representation", "reputation",
	"request", "requirement", "research", "reserve", "resident", "resistance", "resolution",
	"resource", "respect", "response", "responsibility", "rest", "restaurant", "result",
	"retirement", "return", "reveal", "revenue", "revolution", "reward", "rhythm", "rice",
	"roll", "roof", "room", "rope", "rose", "routine", "row", "royalty", "rule", "run",
	"sadness", "salary", "sale", "salt", "sample", "sand", "satisfaction", "sauce", "saving",
	"scale", "scene", "schedule", "scheme", "school", "science", "scope", "score", "scratch",
	"screen", "screw", "script", "sea", "search", "season", "seat", "secret", "section",
	"sector", "security", "selection", "self", "sell", "senior", "sense", "sensitivity",
	"sentence", "sequence", "series", "seriousness", "serve", "session", "set", "setting",
	"settling", "sex", "shadow", "shape", "share", "shelter", "shift", "ship", "shirt",
	"shock", "shoe", "shoot", "shop", "shot", "shoulder", "show", "shower", "side", "sight",
	"significance", "silence", "silver", "simple", "simplicity", "sister", "site", "situation",
	"size", "skill", "skin", "skirt", "sky", "sleep", "slice", "slide", "smile", "smoke",
	"society", "software", "soil", "solution", "song", "sound", "soup", "source", "space",
	"speaker", "specialist", "specificity", "caption", "speed", "spell", "spending", "spirit",
	"spite", "sport", "spot", "spread", "spring", "square", "stability", "staff", "stage",
	"stair", "stamp", "stand", "standard", "star", "start", "state", "statement", "station",
	"status", "stay", "steak", "step", "stick", "still", "stimulation", "stock", "stomach",
	"stone", "storage", "store", "storm", "story", "strain", "strategy", "stream", "strength",
	"stress", "stretch", "strike", "structure", "struggle", "study", "stuff", "style", "subject",
	"submission", "substance", "success", "suffering", "sugar", "suggestion", "suit", "summer",
	"sun", "supermarket", "supply", "support", "surface", "surgery", "surprise", "survey",
	"survival", "sweater", "swimming", "swing", "system", "table", "tactic", "tail", "takeover",
	"talk", "tank", "tap", "target", "task", "taste", "tax", "tea", "teacher", "teaching",
	"team", "tear", "technique", "technology", "teenager", "telephone", "television",
	"temperature", "will", "theory", "tip", "treatment", "vehicle", "vision",
	"temporary", "tennis", "tension", "term", "terrain", "terror", "test", "text", "theme",
	"therapy", "thing", "thought", "threat", "throat", "ticket", "tide", "tie", "tiger", "time",
	"toe", "tone", "tongue", "tool", "tooth", "top", "total", "touch", "tour", "towel",
	"tower", "town", "track", "trade", "tradition", "traffic", "trail", "train", "trainer",
	"transaction", "transfer", "transition", "translation", "transport", "trap", "travel",
	"tree", "trend", "trial", "tribe", "trick", "trip", "troop", "trouble", "truck", "trunk",
	"trust", "truth", "tune", "turn", "twist", "type", "uncertainty", "understanding", "uniform",
	"union", "unit", "universe", "university", "update", "upstairs", "urgency", "use", "utility",
	"vacation", "vacuum", "validity", "valley", "value", "variation", "variety", "vegetable",
	"venture", "version", "victim", "victory", "video", "view", "village", "violence", "virus",
	"visit", "voice", "volume", "volunteer", "vote", "wage", "wait", "wake", "walk", "wall",
	"war", "wardrobe", "warmth", "warning", "warrant", "wash", "waste", "watch", "water", "wave",
	"way", "weakness", "wealth", "weapon", "wear", "weather", "web", "wedding", "week", "weight",
	"welcome", "welfare", "west", "wheel", "whiskey", "white", "whole", "width", "wilderness",
	"win", "wind", "window", "wine", "wing", "winner", "winter", "wisdom", "wish", "withdrawal",
	"witness", "woman", "wonder", "wood", "word", "work", "worker", "workout", "world", "worm",
	"worry", "worth", "wound", "wrap", "wrist", "writer", "writing", "yard", "year", "yellow",
	"youth", "zone", "tire", "title", "toast", "riches", "ride", "ring", "risk", "river",
	"road", "rock", "role", "journey", "judgment", "justice", "kitchen", "knowledge", "land",
	"smell", "smile", "snake", "belief", "bottle"];